#%RAML 1.0 NamedExample
         {
                "customers": [
                  {
                    "identifier": "deb89058-77fb-4e97-8c83-6506c38cacf8",
                    "firstName": "Jason",
                    "lastName": "Bourne",
                    "address":{
                        "identifier": "deb89058-77fb-4e97-8c83-6506c38cacf8",
                        "type": "BILLING",
                        "address": "Main street 122",
                        "city": "San Francisco",
                        "state": "California",
                        "postalCode": "90210",
                        "recipient": "Jason Bourne",
                        "country": "US",
                        "secondaryAddress": "",
                        "mailStopCode": "",
                        "attention": ""
                      }
                  }
                ]
              }